services:
  backend:
    image: gosecureshare.azurecr.io/secure-share-backend:v1
    restart: always
    ports:
      - "80:8080"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - REDIS_ADDR=redis:6379
      - GIN_MODE=release
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
      - redis
  minio:
    image: gosecureshare.azurecr.io/minio:latest
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    ports:
      - "${MINIO_API_PORT}:9000" # S3 API endpoint
      - "${MINIO_CONSOLE_PORT}:9001" # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

  redis:
    image: gosecureshare.azurecr.io/redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
